apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-hello-go
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-web-hello-go
  template:
    metadata:
      labels:
        app: k8s-web-hello-go
    spec:
      containers:
      - name: k8s-web-hello-go
        image: bstashchuk/k8s-web-hello-go
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000