apiVersion: v1
kind: Service
metadata:
  name: k8s-web-to-nginx-go
spec:
  type: LoadBalancer
  selector:
    app: k8s-web-to-nginx-go
  ports:
  - port: 8083
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-to-nginx-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-web-to-nginx-go
  template:
    metadata:
      labels:
        app: k8s-web-to-nginx-go
    spec:
      containers:
      - name: k8s-web-to-nginx-go
        image: asapcal/k8s-web-to-nginx-go:v0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080